[package]
name = "evo"
version = "0.1.0"
authors = ["Joel Lauener <joellauener@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tetra="0.2"
json = "0.12"
rand = "0.7"
